?start: exp

?exp: exp "+" exp1            -> plus
   | exp "-" exp1             -> minus
   | exp1

?exp1: exp1 "*" exp2          -> times
    | exp2

?exp2: "-"exp2                -> negative
    | exp3

?exp3: "log" exp3 "base" exp4 -> logarithm
    | exp3 "^" exp4           -> exponent
    | exp4

?exp4: NUMBER                 -> num
    | "(" exp ")"                                  

%import common.NUMBER
%import common.WS
%ignore WS
