?start: exp

?exp: exp "+" exp1            -> plus
   | exp "-" exp1             -> minus
   | exp1

?exp1: exp1 "*" exp2          -> times
    | exp2

?exp2: "-"exp2                -> negative
    | exp3

?exp3: exp4 "^" exp3          -> exponent
    | exp4

?exp4: "log" exp4 "base" exp5 -> logarithm
    | exp5

?exp5: NUMBER                 -> num
    | "(" exp ")"                                  

%import common.NUMBER
%import common.WS
%ignore WS
